import React, { useState } from 'react';
import styles from './DigitalHealthCheck.module.css';

/* ── Tier data — shown in the stats section ── */
const tiers = [
  {
    id: 'critical',
    label: 'Critical',
    range: '0 – 25',
    color: '#ef4444',
    colorSoft: 'rgba(239,68,68,0.1)',
    icon: '▼',
    headline: 'No online presence',
    description:
      "No website, not listed on Google, and invisible to anyone searching for your service. Competitors with even a basic site are capturing every lead you're missing.",
    stats: [
      { value: '97%', label: 'of consumers search online before calling a local business' },
      { value: '36%', label: 'of small businesses still have no website — and most are losing to ones that do' },
    ],
  },
  {
    id: 'poor',
    label: 'Poor',
    range: '26 – 50',
    color: '#f97316',
    colorSoft: 'rgba(249,115,22,0.1)',
    icon: '▼',
    headline: 'Outdated or broken site',
    description:
      "A website exists but it's slow, not mobile-friendly, or looks unprofessional. Visitors leave before they contact you — often within 3 seconds.",
    stats: [
      { value: '53%', label: 'of mobile users abandon a site that takes longer than 3 seconds to load' },
      { value: '75%', label: 'of people judge a business\'s credibility based on website design alone' },
    ],
  },
  {
    id: 'average',
    label: 'Average',
    range: '51 – 70',
    color: '#eab308',
    colorSoft: 'rgba(234,179,8,0.1)',
    icon: '►',
    headline: 'Functional but not competitive',
    description:
      'The site works, but it\'s not ranking, not converting, and probably built on a template. You\'re visible — just not standing out.',
    stats: [
      { value: '68%', label: 'of online experiences begin with a search engine — is yours optimized?' },
      { value: '2.5x', label: 'more leads generated by businesses with SEO-optimized sites vs those without' },
    ],
  },
  {
    id: 'good',
    label: 'Good',
    range: '71 – 85',
    color: '#22c55e',
    colorSoft: 'rgba(34,197,94,0.1)',
    icon: '►',
    headline: 'Solid foundation',
    description:
      'Your site is mobile-friendly, reasonably fast, and you have some local presence. Small improvements in SEO and performance could significantly increase conversions.',
    stats: [
      { value: '14%', label: 'increase in conversions for every 1-second improvement in page load time' },
      { value: '46%', label: 'of Google searches are for local businesses — local SEO matters more than ever' },
    ],
  },
  {
    id: 'excellent',
    label: 'Excellent',
    range: '86 – 100',
    color: '#00e5ff',
    colorSoft: 'rgba(0,229,255,0.1)',
    icon: '▲',
    headline: 'Competitive & converting',
    description:
      'Fast, found on Google, mobile-first, and built to convert. Your online presence is a real asset — the goal now is staying ahead as competitors catch up.',
    stats: [
      { value: '2x', label: 'more revenue generated by businesses with strong digital presence vs those without' },
      { value: '70%', label: 'of buying decisions are influenced by online content before any human contact' },
    ],
  },
];

/* ── Quiz questions ── */
const questions = [
  {
    id: 'website',
    question: 'Does your business have a website?',
    options: [
      { label: 'No website at all',                  score: 0  },
      { label: 'Yes, but it\'s very outdated',       score: 8  },
      { label: 'Yes, it works but needs improvement', score: 16 },
      { label: 'Yes, and it looks professional',      score: 20 },
    ],
  },
  {
    id: 'mobile',
    question: 'How does your site look on a phone?',
    options: [
      { label: 'No website / haven\'t checked',      score: 0  },
      { label: 'Hard to use on mobile',               score: 4  },
      { label: 'Usable but not great',                score: 8  },
      { label: 'Looks great on all screen sizes',     score: 15 },
    ],
  },
  {
    id: 'speed',
    question: 'How fast does your website load?',
    options: [
      { label: 'No website',                          score: 0  },
      { label: 'Slow — takes 5+ seconds',             score: 3  },
      { label: 'Average — around 3-4 seconds',        score: 7  },
      { label: 'Fast — loads in under 2 seconds',     score: 15 },
    ],
  },
  {
    id: 'google',
    question: 'Do you show up when someone Googles your business type + city?',
    options: [
      { label: 'Not at all',                          score: 0  },
      { label: 'Only if they search my exact name',   score: 8  },
      { label: 'Sometimes, on page 2-3',              score: 14 },
      { label: 'Yes, consistently on page 1',         score: 20 },
    ],
  },
  {
    id: 'gmb',
    question: 'Do you have a Google Business Profile (Google Maps listing)?',
    options: [
      { label: 'No',                                  score: 0  },
      { label: 'Yes, but it\'s incomplete',           score: 5  },
      { label: 'Yes, fully set up with reviews',      score: 10 },
      { label: 'Yes, actively managed with 10+ reviews', score: 15 },
    ],
  },
  {
    id: 'design',
    question: 'How would you describe your current website design?',
    options: [
      { label: 'No website',                          score: 0  },
      { label: 'Looks outdated or unprofessional',    score: 2  },
      { label: 'Clean but generic / template look',   score: 6  },
      { label: 'Professional and on-brand',           score: 10 },
    ],
  },
  {
    id: 'leads',
    question: 'Do you get leads from your website?',
    options: [
      { label: 'No website',                          score: 0  },
      { label: 'Rarely or never',                     score: 1  },
      { label: 'Occasionally',                        score: 3  },
      { label: 'Regularly — it\'s a lead source',     score: 5  },
    ],
  },
];

const MAX_SCORE = questions.reduce((sum, q) =>
  sum + Math.max(...q.options.map((o) => o.score)), 0
);

function getTier(score) {
  const pct = (score / MAX_SCORE) * 100;
  if (pct <= 25) return tiers[0];
  if (pct <= 50) return tiers[1];
  if (pct <= 70) return tiers[2];
  if (pct <= 85) return tiers[3];
  return tiers[4];
}

export default function DigitalHealthCheck({ onNavigate }) {
  const [answers,   setAnswers]   = useState({});
  const [submitted, setSubmitted] = useState(false);

  const answered   = Object.keys(answers).length;
  const totalQ     = questions.length;
  const rawScore   = Object.values(answers).reduce((s, v) => s + v, 0);
  const pct        = Math.round((rawScore / MAX_SCORE) * 100);
  const resultTier = getTier(rawScore);

  const allAnswered = answered === totalQ;

  const handleAnswer = (qId, score) => {
    setAnswers((prev) => ({ ...prev, [qId]: score }));
  };

  const handleSubmit = () => {
    if (allAnswered) setSubmitted(true);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleReset = () => {
    setAnswers({});
    setSubmitted(false);
  };

  return (
    <div className={styles.wrapper}>

      {/* ── PAGE HEADER ── */}
      <div className="section">
        <div className="section-label">// digital health check</div>
        <h2 className={styles.pageTitle}>
          How much is your online<br />presence costing you?
        </h2>
        <p className={styles.pageIntro}>
          Most small businesses have no idea what their digital presence looks like to a potential customer.
          Here's a snapshot of where businesses typically fall — and what it means for their growth.
          Then take the quick quiz below to see where you stand.
        </p>
      </div>

      {/* ── TIER STATS SECTION ── */}
      <section className={styles.tiersSection}>
        <div className={styles.tiersLabel}>
          <div className="section-label">// the spectrum</div>
          <h3 className={styles.tiersTitle}>Where does your business fall?</h3>
        </div>

        <div className={styles.tiersGrid}>
          {tiers.map((tier) => (
            <div
              key={tier.id}
              className={styles.tierCard}
              style={{ borderTopColor: tier.color }}
            >
              <div className={styles.tierTop}>
                <div className={styles.tierLabel} style={{ color: tier.color }}>
                  {tier.label}
                </div>
                <div className={styles.tierRange} style={{ background: tier.colorSoft, color: tier.color }}>
                  {tier.range} pts
                </div>
              </div>

              <h4 className={styles.tierHeadline}>{tier.headline}</h4>
              <p className={styles.tierDesc}>{tier.description}</p>

              <div className={styles.tierStats}>
                {tier.stats.map((s) => (
                  <div key={s.label} className={styles.tierStat}>
                    <div className={styles.tierStatVal} style={{ color: tier.color }}>
                      {s.value}
                    </div>
                    <div className={styles.tierStatLabel}>{s.label}</div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ── QUIZ SECTION ── */}
      <section className={styles.quizSection}>
        <div className={styles.quizHeader}>
          <div className="section-label">// the quiz</div>
          <h3 className={styles.quizTitle}>
            {submitted ? 'Your digital health score' : 'Check your own score'}
          </h3>
          {!submitted && (
            <p className={styles.quizIntro}>
              Answer {totalQ} quick questions to see exactly where your online presence stands
              and what it might be costing you.
            </p>
          )}
        </div>

        {submitted ? (
          /* ── RESULT ── */
          <div className={styles.result}>
            <div className={styles.resultScoreWrap}>
              <div
                className={styles.resultScoreRing}
                style={{ borderColor: resultTier.color }}
              >
                <div className={styles.resultScoreNum} style={{ color: resultTier.color }}>
                  {pct}
                </div>
                <div className={styles.resultScoreLabel}>out of 100</div>
              </div>
              <div className={styles.resultMeta}>
                <div
                  className={styles.resultTierBadge}
                  style={{ background: resultTier.colorSoft, color: resultTier.color, border: `1px solid ${resultTier.color}` }}
                >
                  {resultTier.icon} {resultTier.label}
                </div>
                <h4 className={styles.resultHeadline}>{resultTier.headline}</h4>
                <p className={styles.resultDesc}>{resultTier.description}</p>
              </div>
            </div>

            {/* Score bar */}
            <div className={styles.scoreBar}>
              <div className={styles.scoreBarFill} style={{ width: `${pct}%`, background: resultTier.color }} />
              <div className={styles.scoreBarMarkers}>
                {tiers.map((t) => (
                  <div key={t.id} className={styles.scoreBarMarker} style={{ color: t.color }}>
                    {t.label}
                  </div>
                ))}
              </div>
            </div>

            {/* Tier stats for their result */}
            <div className={styles.resultStats}>
              {resultTier.stats.map((s) => (
                <div key={s.label} className={styles.resultStat} style={{ borderLeftColor: resultTier.color }}>
                  <div className={styles.resultStatVal} style={{ color: resultTier.color }}>{s.value}</div>
                  <div className={styles.resultStatLabel}>{s.label}</div>
                </div>
              ))}
            </div>

            {/* CTA */}
            <div className={styles.resultCta}>
              <p className={styles.resultCtaText}>
                Want to know exactly how to improve your score? We'll give you a free,
                no-pressure audit with specific recommendations for your business.
              </p>
              <div className={styles.resultCtaBtns}>
                <button className="btn-primary" onClick={() => onNavigate('contact')}>
                  Get a Free Site Audit →
                </button>
                <button className={styles.retakeBtn} onClick={handleReset}>
                  Retake quiz
                </button>
              </div>
            </div>
          </div>
        ) : (
          /* ── QUESTIONS ── */
          <div>
            <div className={styles.progressBar}>
              <div
                className={styles.progressFill}
                style={{ width: `${(answered / totalQ) * 100}%` }}
              />
            </div>
            <div className={styles.progressLabel}>
              {answered} of {totalQ} answered
            </div>

            <div className={styles.questions}>
              {questions.map((q, qi) => (
                <div key={q.id} className={styles.question}>
                  <div className={styles.questionNum}>
                    {String(qi + 1).padStart(2, '0')}
                  </div>
                  <div className={styles.questionBody}>
                    <h4 className={styles.questionText}>{q.question}</h4>
                    <div className={styles.options}>
                      {q.options.map((opt) => (
                        <button
                          key={opt.label}
                          className={`${styles.option} ${answers[q.id] === opt.score ? styles.optionSelected : ''}`}
                          onClick={() => handleAnswer(q.id, opt.score)}
                          aria-pressed={answers[q.id] === opt.score}
                        >
                          <span className={styles.optionDot} aria-hidden="true" />
                          {opt.label}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              ))}
            </div>

            <div className={styles.submitRow}>
              <button
                className="btn-primary"
                onClick={handleSubmit}
                disabled={!allAnswered}
                aria-disabled={!allAnswered}
              >
                {allAnswered
                  ? 'See my score →'
                  : `Answer all questions to continue (${totalQ - answered} remaining)`}
              </button>
            </div>
          </div>
        )}
      </section>

    </div>
  );
}
